### ISSUE TITLE
Crashing on trying to find new channel

### ISSUE THREAD

**Issue by Reserton** [Zaarrg/TTVDropBot#16]
There seems to be an issue when you already have the drop. I have 1.3.2.2 Hot Fix 2

It doesn't seem to scan for drops you already have and only channel up currently is ArikaSaki. When it watches it seems to finally decide I must already have the drop. however then just completely fails to find another channel and crashes as below.

Watching https://www.twitch.tv/AriaSaki...

Current Progress: - % | Try: 1
Current Progress: - % | Try: 2

Failed to get a valid Drop to progress on this Channel or it is already claimed... Looking for a new one...

Checking for Live Channels

Going to Starting Channel...
(node:20552) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Invalid parameters Failed to deserialize params.url - BINDINGS: mandatory field missing at position 49
    at S:\Downloads\TTVDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (S:\Downloads\TTVDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at next (S:\Downloads\TTVDropBot\node_modules\puppeteer-extra-plugin-stealth\evasions\sourceurl\index.js:30:43)
    at CDPSession.send (S:\Downloads\TTVDropBot\node_modules\puppeteer-extra-plugin-stealth\evasions\sourceurl\index.js:46:18)
    at navigate (S:\Downloads\TTVDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:108:47)
    at FrameManager.navigateFrame (S:\Downloads\TTVDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:91:13)
    at Frame.goto (S:\Downloads\TTVDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:416:41)
    at Page.goto (S:\Downloads\TTVDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:789:53)
    at StreamPage (S:\Downloads\TTVDropBot\src\Pages\StreamPage.js:26:24)
(Use `TTVDropBot --trace-warnings ...` to show where the warning was created)
(node:20552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Reserton** [comment]
This seems to only happen if there is no other streams to watch. Works fine when multiple online.

**Comment by Zaarrg** [comment]
Fixed it with the release of [1.3.3](https://github.com/Zaarrg/TTVDropBot/releases)

What was happening:
The Bot was avoding to watch the same channel twice and if there is only one ch live the bot did not find any onther channel therefor errored. Fixed by letting the bot watch the same ch if there is only one live and wait of new ch to come online.
