### ISSUE TITLE
MacOS issue

### ISSUE THREAD

**Issue by akaigua** [Zaarrg/TTVDropBot#33]
So I tried to use this software on MacOS the chrome login stuff is all doing well but after i start watching an error occurred 
```
`Watching` https://www.twitch.tv/rainbow6latam...
 
/Users/songboyao/Downloads/TTVDropBot-main/src/Pages/StreamCustomPage.js:267
    const Pointscontent = await Points.getProperty('textContent')
                                       ^

TypeError: Cannot read property 'getProperty' of undefined
    at farmpoint (/Users/songboyao/Downloads/TTVDropBot-main/src/Pages/StreamCustomPage.js:267:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/songboyao/Downloads/TTVDropBot-main/src/Pages/StreamCustomPage.js:111:13
    at async /Users/songboyao/Downloads/TTVDropBot-main/src/Pages/StreamCustomPage.js:80:9
    at async CurrentProgressEvent (/Users/songboyao/Downloads/TTVDropBot-main/src/Pages/StreamCustomPage.js:78:5)
    at async StreamCustomPage (/Users/songboyao/Downloads/TTVDropBot-main/src/Pages/StreamCustomPage.js:67:5)
    at async /Users/songboyao/Downloads/TTVDropBot-main/src/Pages/WatchingPage.js:44:17
    at async /Users/songboyao/Downloads/TTVDropBot-main/src/Pages/WatchingPage.js:37:9
    at async Watch (/Users/songboyao/Downloads/TTVDropBot-main/src/Pages/WatchingPage.js:23:5)
```

**Comment by Zaarrg** [comment]
Issue should not occur anymore, was an issue only in older versions of the bot which were using xpaths.
