### ISSUE TITLE
Can't login via command line

### ISSUE THREAD

**Issue by daeeros** [Zaarrg/TTVDropBot#57]
```
? What is your Password? [hidden]

Something went wrong...
Login failed for an unknown reason...
The Reason is probably:
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'error_code' of undefined
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:221:95
      at Generator.next (<anonymous>)
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:8:71
      at new Promise (<anonymous>)
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:4:12
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:160:20
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    [stack]: "TypeError: Cannot read property 'error_code' of undefined\n" +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:221:95\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:8:71\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:4:12\n' +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:160:20\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
    [message]: "Cannot read property 'error_code' of undefined"
  }
}
Unhandled Rejection Reason: TypeError: Cannot read property 'error_code' of undefined
```

I entering current information, buy getting this

**Comment by Zaarrg** [comment]
What version of the bot are you using? 
Does Login via the browser work for you?
And do you use 2Auth ?

**Comment by Hinkiii** [comment]
I have this issue,
browser login returns: "Something went wrong. Please try again."
2FA is not active.
