### ISSUE TITLE
Unhandled Rejection at: Promise           Frequent crashes with errors like this

### ISSUE THREAD

**Issue by xperisa** [Zaarrg/TTVDropBot#71]
Unhandled Rejection at: Promise {
  <rejected> FetchError: request to https://gql.twitch.tv/integrity failed, reason: connect ETIMEDOUT 199.232.18.167:443
      at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (node:events:513:28)
      at TLSSocket.socketErrorListener (node:_http_client:481:9)
      at TLSSocket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    message: 'request to https://gql.twitch.tv/integrity failed, reason: connect ETIMEDOUT 199.232.18.167:443',
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    [stack]: 'FetchError: request to https://gql.twitch.tv/integrity failed, reason: connect ETIMEDOUT 199.232.18.167:443\n' +
      '    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1491:11)\n' +
      '    at ClientRequest.emit (node:events:513:28)\n' +
      '    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n' +
      '    at TLSSocket.emit (node:events:513:28)\n' +
      '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
      '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
    name: 'FetchError'
  }
}
Unhandled Rejection Reason: FetchError: request to https://gql.twitch.tv/integrity failed, reason: connect ETIMEDOUT 199.232.18.167:443

**Comment by herhor67** [comment]
I am getting the same, so now Im almost certain its not a fault on my side.
![image](https://user-images.githubusercontent.com/7432818/190910669-244f1eaa-b4f5-4cc9-a6cc-b045ecf6ef09.png)

**Comment by xperisa** [comment]
> I am getting the same, so now Im almost certain its not a fault on my side. ![image](https://user-images.githubusercontent.com/7432818/190910669-244f1eaa-b4f5-4cc9-a6cc-b045ecf6ef09.png) ![image](https://user-images.githubusercontent.com/7432818/190910708-717c91b8-495b-4788-9642-932c00ff60e1.png)

Many people have encountered this problem
