### ISSUE TITLE
cant log in either way

### ISSUE THREAD

**Issue by connormcginty** [Zaarrg/TTVDropBot#79]
When loggings in - using command line it crashes
when logging in via browser, twitch won't accept my correct credentials

**Comment by redr00t** [comment]
same here

**Comment by KingYam** [comment]
Also having the same problem, here is output from _TTVDropBot-error.txt_
```
2022-10-06 09:32:15: Unhandled Rejection at: Promise {
  <rejected> Error: Navigation failed because browser has disconnected!
      at new LifecycleWatcher (C:\snapshot\TTVDropBot-v2\node_modules\puppeteer-core\lib\cjs\puppeteer\common\LifecycleWatcher.js:95:223)
      at Frame.waitForNavigation (C:\snapshot\TTVDropBot-v2\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:261:25)
      at Page.waitForNavigation (C:\snapshot\TTVDropBot-v2\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:1218:88)
      at C:\snapshot\TTVDropBot-v2\build\Pages\loginPage.js:38:29
      at Generator.next (<anonymous>)
      at fulfilled (C:\snapshot\TTVDropBot-v2\build\Pages\loginPage.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    [stack]: 'Error: Navigation failed because browser has disconnected!\n' +
      '    at new LifecycleWatcher (C:\\snapshot\\TTVDropBot-v2\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\LifecycleWatcher.js:95:223)\n' +
      '    at Frame.waitForNavigation (C:\\snapshot\\TTVDropBot-v2\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:261:25)\n' +
      '    at Page.waitForNavigation (C:\\snapshot\\TTVDropBot-v2\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Page.js:1218:88)\n' +
      '    at C:\\snapshot\\TTVDropBot-v2\\build\\Pages\\loginPage.js:38:29\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (C:\\snapshot\\TTVDropBot-v2\\build\\Pages\\loginPage.js:5:58)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
    [message]: 'Navigation failed because browser has disconnected!'
  }
}
2022-10-06 09:32:24: Something went wrong...
```

**Comment by LukysGaming** [comment]
+1

**Comment by jennyfercaron** [comment]
I have the same problem

**Comment by bossman90** [comment]
+1

**Comment by NotFrostal** [comment]
+1

**Comment by Suitingyak** [comment]
+1

**Comment by jlw4049** [comment]
Same

**Comment by TomerGamerTV** [comment]
i get something went wrong error

**Comment by cyberofficial** [comment]
* Work Around for Unable to log in
     * Create a file called **twitch-session.json** under the same directory of the application
     * Paste this inside the file `[{"name":"auth-token","value":"replaceme"}]`
     * Get a browser addon that can look at cookies, {Addons: [Opera](https://addons.opera.com/en/extensions/details/cookie-editor-2/), [Chrome](https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm?hl=en), [Firefox](https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/)}
     * Copy the `auth-token` and replace `replaceme` with your token
![](https://i.imgur.com/1kj32dP.png)
     * Save and close the editor you used then relaunch the application.

**Comment by mrtsntrk** [comment]
@cyberofficial dude your method is successful.

**Comment by MiranoVerhoef** [comment]
@cyberofficial 

I have downloaded your patched version but I’m getting the same errors as the post owner, 
![image](https://user-images.githubusercontent.com/67699857/194563181-e65d0d92-d517-489e-90f9-3a3f8baf93d8.jpg)

**Comment by xeryax** [comment]
> * Work Around for Unable to log in
on chrome, can also hit F12, under the application tab there should be a 'cookies' section with https://www.twitch.tv in it.  that has the auth-code as well

**Comment by LPRM** [comment]
> @cyberofficial
> 
> I have downloaded your patched version but I’m getting the same errors as the post owner, ![image](https://user-images.githubusercontent.com/67699857/194563181-e65d0d92-d517-489e-90f9-3a3f8baf93d8.jpg)

I have this issue too.

**Comment by LukysGaming** [comment]
We'll have to wait for the owner to update it i guess

**Comment by cyberofficial** [comment]
> @cyberofficial
> 
> I have downloaded your patched version but I’m getting the same errors as the post owner, ![image](https://user-images.githubusercontent.com/67699857/194563181-e65d0d92-d517-489e-90f9-3a3f8baf93d8.jpg)


> > @cyberofficial
> > I have downloaded your patched version but I’m getting the same errors as the post owner, ![image](https://user-images.githubusercontent.com/67699857/194563181-e65d0d92-d517-489e-90f9-3a3f8baf93d8.jpg)
> 
> I have this issue too.

If you have my latest build [00.03](https://github.com/cyberofficial/TTVDropBot/releases/tag/00.02-hotfix)
Disable channel point collection, (feature i placed in)

Inside **settings.json** add the line `"CollectPoints": false` (will add argument for cli soon)
Example:
![](https://i.imgur.com/d55cFxO.png)

**Comment by LPRM** [comment]
> > @cyberofficial
> > I have downloaded your patched version but I’m getting the same errors as the post owner,
> 
> > > @cyberofficial
> > > I have downloaded your patched version but I’m getting the same errors as the post owner,
> > 
> > 
> > I have this issue too.
> 
> If you have my latest build [00.03](https://github.com/cyberofficial/TTVDropBot/releases/tag/00.02-hotfix) Disable channel point collection, (feature i placed in)
> 
> Inside **settings.json** add the line `"CollectPoints": false` (will add argument for cli soon) Example: ![](https://camo.githubusercontent.com/4466e1fa6f31cb2cca8c5ebf618c7b8c626a8563b9cd8f07358c7f9124505f1e/68747470733a2f2f692e696d6775722e636f6d2f6435356346784f2e706e67)
> 
> If that doesn't work, i can try a few other methods, but channels points seem to cause many errors right now



I have "CollectPoints": false already, scrrenshot below:

![Screenshot 2022-10-07 191600](https://user-images.githubusercontent.com/21993115/194623486-e1617315-354a-4055-913f-65d7235327df.png)

**Comment by cyberofficial** [comment]
> > > @cyberofficial
> > > I have downloaded your patched version but I’m getting the same errors as the post owner,
> > 
> > 
> > > > @cyberofficial
> > > > I have downloaded your patched version but I’m getting the same errors as the post owner,
> > > 
> > > 
> > > I have this issue too.
> > 
> > 
> > If you have my latest build [00.03](https://github.com/cyberofficial/TTVDropBot/releases/tag/00.02-hotfix) Disable channel point collection, (feature i placed in)
> > Inside **settings.json** add the line `"CollectPoints": false` (will add argument for cli soon) Example: ![](https://camo.githubusercontent.com/4466e1fa6f31cb2cca8c5ebf618c7b8c626a8563b9cd8f07358c7f9124505f1e/68747470733a2f2f692e696d6775722e636f6d2f6435356346784f2e706e67)
> > If that doesn't work, i can try a few other methods, but channels points seem to cause many errors right now
> 
> I have "CollectPoints": false already, scrrenshot below:
> 
> ![Screenshot 2022-10-07 191600](https://user-images.githubusercontent.com/21993115/194623486-e1617315-354a-4055-913f-65d7235327df.png)

You issue means your auth code is incorrect or expired; you need to generate a new code and update **twitch-session.json**

**Comment by LPRM** [comment]
> > > > @cyberofficial
> > > > I have downloaded your patched version but I’m getting the same errors as the post owner,
> > > 
> > > 
> > > > > @cyberofficial
> > > > > I have downloaded your patched version but I’m getting the same errors as the post owner,
> > > > 
> > > > 
> > > > I have this issue too.
> > > 
> > > 
> > > If you have my latest build [00.03](https://github.com/cyberofficial/TTVDropBot/releases/tag/00.02-hotfix) Disable channel point collection, (feature i placed in)
> > > Inside **settings.json** add the line `"CollectPoints": false` (will add argument for cli soon) Example:
> > > If that doesn't work, i can try a few other methods, but channels points seem to cause many errors right now
> > 
> > 
> > I have "CollectPoints": false already, scrrenshot below:
> > ![Screenshot 2022-10-07 191600](https://user-images.githubusercontent.com/21993115/194623486-e1617315-354a-4055-913f-65d7235327df.png)
> 
> Your issue means your auth-token is incorrect or expired; you need to generate a new code and update **twitch-session.json** using the work around method i posted.
> 
> * make sure to relog into twitch and click the box that says keep me logged in for 30 days for a longer lasting auth-token

I had just logged in with that token, tried again with new token and now works. Thank you

**Comment by MiranoVerhoef** [comment]
Did the way you said, with the cookie editor, but the error still comes back unfortunately

**Comment by MiranoVerhoef** [comment]
@cyberofficial do you have a other cause of the error?

mice verified with disable collect points as well!

**Comment by TomerGamerTV** [comment]
i tried using the cookie but the app seem to crash than i try to watch any stream

**Comment by cyberofficial** [comment]
> @cyberofficial do you have a other cause of the error?
> 
> mice verified with disable collect points as well!

@MiranoVerhoef Can you send the logs?

**Comment by MiranoVerhoef** [comment]
@cyberofficial let me get them once I’m home!

**Comment by bossman90** [comment]
Any news?

**Comment by omeganot** [comment]
I too had that DropsPage_ClaimDropsReward error.  What cleared it for me was removing the Docker container and creating it fresh with my updated auth_token.  This might not help you if you're not using Docker, but there could be some caching going on somewhere that needs cleared out.

**Comment by 2relativ** [comment]
Can confirm this issue is still there. Also @cyberofficial since your build does not support command line yet, I had to use another way: I set the claim timer to like 6000000 xD this way it keeps watching and afterwards i just have to remember claiming :D the autoclaim variable didn't work for me :/  btw, running this on Ubuntu with displayless activated. Runs as a systemd task. It retrys 5 times and after that it stops. In my linux cockpit i can simply start the process from my smartphone. Thats good enough for me at the moment :D
