### ISSUE TITLE
Cannot read property 'error_code' of undefined

### ISSUE THREAD

**Issue by Dr0mus** [Zaarrg/TTVDropBot#80]
```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'error_code' of undefined
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:221:95
      at Generator.next (<anonymous>)
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:8:71
      at new Promise (<anonymous>)
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:4:12
      at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:154:20
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    [stack]: "TypeError: Cannot read property 'error_code' of undefined\n" +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:221:95\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:8:71\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:4:12\n' +
      '    at /snapshot/TTVDropBot-v2/build/functions/login/defaultlogin.js:154:20\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
    [message]: "Cannot read property 'error_code' of undefined"
  }
}
Unhandled Rejection Reason: TypeError: Cannot read property 'error_code' of undefined
```

^ is the error I am getting. I don't have 2FA, it is a fresh install. Trying to login via the command line.

**Comment by impulsivus** [comment]
#79

**Comment by Dr0mus** [comment]
> #79

ty
